name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build Wrapper for SonarQube
      run: |
        build-wrapper-linux-x86-64 --out-dir bw-output cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
        build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build

    - name: Run Tests and Coverage
      run: |
        cd build
        ctest --output-on-failure
        gcovr -r . --xml-pretty --output coverage.cobertura.xml

    - name: SonarQube Analysis
      uses: sonarsource/sonarqube-scan-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: SonarQube Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
